### ISSUE TITLE
Question on use of GAN and customization of surrogates 

### ISSUE THREAD

**Issue by ZIB012** [Crunch-UQ4MI/neuraluq#14]
Hi,
I found out your library and I was playing a little bit. I found very interesting the customization of surrogates and the training of a GAN to learn functional prior, but I didn't understand how to use it outside the example proposed. 
For example, considering a model similar to the KO example, and considering the case where I have 11 available measurements of X1 and X3, and only 3/4 available measurements for X2, is it possible, and if yes how, to use the above idea to reduce the variance of the reconstructed solution?
Thank you

**Comment by ZongrenZou** [comment]
> Hi, I found out your library and I was playing a little bit. I found very interesting the customization of surrogates and the training of a GAN to learn functional prior, but I didn't understand how to use it outside the example proposed. For example, considering a model similar to the KO example, and considering the case where I have 11 available measurements of X1 and X3, and only 3/4 available measurements for X2, is it possible, and if yes how, to use the above idea to reduce the variance of the reconstructed solution? Thank you

GANs are used to learn a family of functions or stochastic processes, after which some data from a specific sample from that family, or a realization of the stochastic processes, is used to identify the function. This is the general philosophy of the functional prior framework. 

Regarding the KO example you mentioned, I would suggest making the KO system stochastic first, by, for example, either assuming its initial conditions come from a distribution, say normal or uniform, and train a GAN to learn the solutions to the systems. Then, we can use a few measurements from one specific solution to the KO system to reconstruct the solution.

**Comment by ZIB012** [comment]
Thanks a lot for the response.
