### ISSUE TITLE
Installation in Anaconda-Spyder

### ISSUE THREAD

**Issue by katayooneshkofti** [Crunch-UQ4MI/neuraluq#8]
Hi @ZongrenZou 
When I want to install the library, this error appears: 
`ERROR: Could not find a version that satisfies the requirement neuraluq (from versions: none)
ERROR: No matching distribution found for neuraluq`

**Comment by ZongrenZou** [comment]
> Hi @ZongrenZou When I want to install the library, this error appears: `ERROR: Could not find a version that satisfies the requirement neuraluq (from versions: none) ERROR: No matching distribution found for neuraluq`

Hi, did you do "python setup.py install"? The error seems to imply that you did "pip install neuraluq" or "conda install neuraluq". Currently, NeuralUQ is not pip compatible. So to install the library, you need to download the repo (or use git clone), navigate to the directory where neuraluq/ and setup.py are stored, and then type "python setup.py install" in your command line. 

Sorry for the inconvenience. Let me know it still does not work.

**Comment by katayooneshkofti** [comment]
Thank you for your comprehensive explanation. I managed to install it through git clone.
